apiVersion: v1
kind: Service
metadata:
  name: baahubali-mongo-qa-svc-a
  labels:
    name: baahubali-mongo-qa-svc-a
spec:
  type: LoadBalancer
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
    name: baahubali-mongo-qa-svc-a
  selector:
    name: baahubali-mongo-qa-node1
    instance: rod
---
apiVersion: v1
kind: Service
metadata:
  name: baahubali-mongo-qa-svc-b
  labels:
    name: baahubali-mongo-qa-svc-b
spec:
  type: LoadBalancer
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
    name: baahubali-mongo-qa-svc-b
  selector:
    name: baahubali-mongo-qa-node2
    instance: jane
---
apiVersion: v1
kind: Service
metadata:
  name: baahubali-mongo-qa-svc-c
  labels:
    name: baahubali-mongo-qa-svc-c
spec:
  type: LoadBalancer
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
    name: baahubali-mongo-qa-svc-c
  selector:
    name: baahubali-mongo-qa-node3
    instance: freddy
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: baahubali-mongo-qa-rc1
  labels:
    name: baahubali-mongo-qa-rc
spec:
  replicas: 1
  selector:
    name: baahubali-mongo-qa-node1
  template:
    metadata:
      labels:
        name: baahubali-mongo-qa-node1
        instance: rod
    spec:
      containers:
      - name: baahubali-mongo-qa-node1
        image: mongo
        command:
         - mongod
         - "--replSet"
         - baahubali_qa_replica_set
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: baahubali-mongo-qa-persistent-storage1
          mountPath: /data/db
      volumes:
      - name: baahubali-mongo-qa-persistent-storage1
        persistentVolumeClaim:
          claimName: baahubali-qa-mongo1
           
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: baahubali-mongo-qa-rc2
  labels:
    name: baahubali-mongo-qa-rc
spec:
  replicas: 1
  selector:
    name: baahubali-mongo-qa-node2
  template:
    metadata:
      labels:
        name: baahubali-mongo-qa-node2
        instance: jane
    spec:
      containers:
      - name: baahubali-mongo-qa-node2
        image: mongo
        command:
         - mongod
         - "--replSet"
         - baahubali_qa_replica_set
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: baahubali-mongo-qa-persistent-storage2
          mountPath: /data/db
      volumes:
      - name: baahubali-mongo-qa-persistent-storage2
        persistentVolumeClaim:
          claimName: baahubali-qa-mongo2
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: baahubali-mongo-qa-rc3
  labels:
    name: baahubali-mongo-qa-rc
spec:
  replicas: 1
  selector:
    name: baahubali-mongo-qa-node3
  template:
    metadata:
      labels:
        name: baahubali-mongo-qa-node3
        instance: freddy
    spec:
      containers:
      - name: baahubali-mongo-qa-node3
        image: mongo
        command:
         - mongod
         - "--replSet"
         - my_replica_set
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: baahubali-mongo-qa-persistent-storage3
          mountPath: /data/db
      volumes:
      - name: baahubali-mongo-qa-persistent-storage3
        persistentVolumeClaim:
          claimName: baahubali-qa-mongo3
